--- 
- hosts: webserver
  become: true
  tasks:  
    - name: Install JDK
      apt:  name=openjdk-8-jdk state=present update_cache=yes
      tags: package

    - name: Install GIT
      apt:  name=git state=present update_cache=yes
      tags: package

    - name: Install Maven
      apt:  name=maven state=present update_cache=yes
      tags: package

    - name: Pull Repository
      git:  repo='https://github.com/hany-abdelrahman/example-spring.git' dest=/home/server/ force=yes
      tags: code

    - name: Pull MySQL from docker  
      docker_image:
        name: library/mysql

    - name: Start Mysql 
      command: docker run -d -p 3306:3306 -e MYSQL_USER=dbuser -e MYSQL_PASSWORD=dbpassword -e MYSQL_DATABASE=viewsdb -e MYSQL_ROOT_PASSWORD=rootpassword --name labfirst_mysql mysql

    - name: Wait for database to be available
      command: docker exec labfirst_mysql mysqladmin ping -uroot -prootpassword
      register: result
      until: result.rc == 0
      retries: 10
      delay: 5
              
    - name: Launch Spring Server
      shell: nohup mvn -f /home/server/pom.xml clean install spring-boot:start -Dfork=true
      tags: launch, launch-server 
