---
- hosts: master,slaves
  become: true
  gather_facts: no
  tasks:
    - name: Install GIT
      apt:  name=git state=present update_cache=yes

    - name: Pull Repository
      git:  repo='https://github.com/hany-abdelrahman/docker-locust.git' dest=/home/repos/ force=yes

    - name: Build Docker Image
      docker_image:
        path: /home/repos/
        name: locust
      tags: build-image

    - name: Copy Locust File
      template: src=./locust-files/test-random.j2 dest=/home/repos/locustfiles/test.py

- hosts: master
  become: true
  tasks:
    - name: Start Master Node
      command: docker run -d -p 8089:8089 -p 5557:5557 -p 5558:5558 -v /home/repos/locustfiles:/opt/locustfiles locust locust --master -f /opt/locustfiles/test.py
      tags: start-master

- hosts: slaves
  become: true
  tasks:
    - name: Start Slaves Nodes
      command: docker run -d --net="host" -p 5557:5557 -p 5558:5558 -v /home/repos/locustfiles:/opt/locustfiles locust locust --slave --master-host="{{groups['master'][0]}}" -f /opt/locustfiles/test.py
      tags: start-slaves
