--- 
- hosts: loadbalancer
  become: true
  tasks:  
    - name: Install JDK
      yum:  name=java-1.7.0-openjdk state=latest
      tags: package

    - name: Install GIT
      yum:  name=git state=present update_cache=yes
      tags: package

    - name: Add maven repo
      get_url: url=http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo dest=/etc/yum.repos.d/epel-apache-maven.repo
  
    - name: Install Maven
      yum:  name=apache-maven state=present update_cache=yes
      tags: package

    - name: Increase Open Files Soft Limit
      pam_limits: domain=* limit_type=soft limit_item=nofile value=100240 	

    - name: Increase Open Files Hard Limit
      pam_limits: domain=* limit_type=hard limit_item=nofile value=100240 	

    - name: Pull Repository
      git:  repo='https://github.com/hany-abdelrahman/scalability-loadbalancer.git' dest=/home/server/ force=yes
      tags: code

    - name: Copy Properties File
      template: src=./templates/loadbalancer.application.properties.j2 dest=/home/server/src/main/resources/application.properties

    - name: Build Project with maven
      shell: mvn -f /home/server/pom.xml clean install -DskipTests
      
    - name: Launch Spring Server
      shell: nohup java -jar /home/server/target/loadbalancer-0.0.1-SNAPSHOT.jar -DskipTests &
      tags: launch, launch-server 
