--- 
- hosts: webserver
  become: true
  tasks:  
    - name: Install JDK
      apt:  name=openjdk-8-jdk state=present update_cache=yes
      tags: package

    - name: Install GIT
      apt:  name=git state=present update_cache=yes
      tags: package

    - name: Install Maven
      apt:  name=maven state=present update_cache=yes
      tags: package

    - name: Pull Repository
      git:  repo='https://github.com/hany-abdelrahman/example-spring.git' dest=/home/server/ force=yes
      tags: code

    - name: Copy Properties File
      template: src=./templates/application.properties.j2 dest=/home/server/src/main/resources/application.properties
      
    - name: Launch Spring Server
      shell: nohup mvn -f /home/server/pom.xml clean install spring-boot:start -Dfork=true
      tags: launch, launch-server 
