---
- include: init-local.yml
- include: launch-instances.yml
- include: add-python.yml
- include: add-docker.yml
- include: launch-ambari.yml
- include: launch-htrace.yml
- include: launch-zipkin.yml
- include: launch-grafana.yml
- include: launch-loadbalancer.yml
- include: launch-server.yml
- include: launch-locust.yml
