---
- include: init-local.yml
- include: launch-instances.yml
- include: add-python.yml
- include: add-docker.yml
- include: launch-grafana.yml
- include: launch-server.yml
- include: launch-locust.yml
