---
#- include: init-local.yml
#- include: launch_instances.yml
- include: add-python.yml
- include: add-docker.yml
- include: launch-database.yml
- include: launch-server.yml
- include: launch-locust.yml
