-- include ec2_launch_server.yml
-- include ec2_launch_master.yml
-- include ec2_launch_slaves.yml
-- include add_python.yml
-- include add-docker.yml
-- include launch-server.yml
-- include launch-locust.yml
