---
# tasks file for launch_ec2
- name: Amazon EC2 | Create Key Pair
  ec2_key:
    name: "{{ keypair }}"
    region: "{{ region }}"
    key_material: "{{ item }}"
  with_file: "{{aws_key}}"

- name: Create a security group
  tags: security
  local_action: 
    module: ec2_group
    name: "{{ security_group }}"
    description: Security Group for webserver Servers
    region: "{{ region }}"
    rules:
      - proto: all
        from_port: -1
        to_port: -1
        cidr_ip: 0.0.0.0/0

    rules_egress:
      - proto: all
        from_port: -1
        to_port: -1
        cidr_ip: 0.0.0.0/0

- name: Launch the new EC2 Instance
  local_action: ec2 
                group={{ security_group }} 
                instance_type={{ instance_type}} 
                image={{ image }} 
                wait=true 
                region={{ region }} 
                keypair={{ keypair }}
                count={{count}}
  register: ec2

- name: Add the newly created EC2 instance(s) to the corresponding host group (located inside the directory)
  local_action: lineinfile 
                dest="./hosts" 
                regexp={{item.public_ip}} 
                insertafter="{{host_group}}" line="{{item.public_ip}}" state=present
  with_items: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  local_action: wait_for 
                host={{ item.public_ip }} 
                port=22 
                delay=60 
                timeout=320
                state=started
  with_items: "{{ ec2.instances }}"

- name: Add tag to Instance(s)
  local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present
  with_items: "{{ ec2.instances }}"
  args:
    tags:
      Name: "{{instance_tag}}"
